#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
trap "rm -f .git/tags.$$" EXIT
ctags --tag-relative -Rf.git/tags.$$ --exclude=*/node_modules/* --languages=-javascript,sql,html,c,coffee
mv .git/tags.$$ .git/tags
