# sl
# Autogenerated from man page /usr/local/share/man/man1/sl.1
# using Deroffing man parser
complete -c sl -s a --description 'An accident is occurring.  People cry for help.'
complete -c sl -s l --description 'Little version.'
complete -c sl -s F --description 'It flies like the galaxy express 999.'
complete -c sl -s c --description 'C51 appears instead of D51.'

